version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/usr/src/app
    command: python bot.py
    ports:
      - "8080:8080"
